program: sweep_interface.py
method: grid
name: clean
metric:
    name: asr_acc
    goal: maximize
    
parameters:
    seed:  
        value: 0
    lr: 
        values: [0.01]
    gamma:  
        values: [1]
    lr_method:  
        values: ['linear']
    target_lr:  
        values: [0.02]
    momentum:   
        values: [0.9]
    decay:   
        values: [0.0005]
    batch_size: 
        values: [64]
    test_batch_size:
        values: [1024]
    num_worker:
        value: 2
    num_sampled_participants:   
        value: 10
    sample_method:  
        values: ['random']
    sample_poison_ratio:    
        values: [0]
    dirichlet_alpha:    
        values: [0.9]
    retrain_times:  
        values: [2]
    attacker_retrain_times: 
        values: [2]
    save_every:     
        value: 10000
    attacker_method:   
        values: ['sin-adv']
    malicious_update_method:
        values: ['label']
    agg_method:     #avg,clip,fedprox,fednova,dp,krum,multkrum，bulyan,rfa
        values: ['avg']
    mu:     #fedprox参数
        values: [0.01]
    clip_factor:    
        values: [1]
    attacker_lr_decay:
        values: [5]
    trigger_lr:    
        values: [0.01]
    load_benign_model:  
        values: [true]
    adv_loss:
        values: ['ce']
    dm_type:
        values: ['none']
    dm_adv_epochs:  
        values: [5]
    dm_adv_K:
        values: [1]
    dm_adv_model_count: 
        values: [1]
    noise_model_count:
        values: [9]
    noise_loss_lambda:  
        values: [0.01]
    wp_factor:
        values: [0.05]
    trigger_path:   
        values: ['']
    attack_type:    
        values: ['my']
    is_log:         
        values: [false]
    l_inf:          
        values: [16]
    trigger_x:
        values: [0]
    trigger_y:
        values: [0]
    trigger_outter_epochs:  
        values: [150]
    poison_start_epoch: 
        values: [1900]
    epochs:        
        values: [1100]
    poison_epochs:  #投毒训练epochs总数
        values: [100]
    num_total_participants: #客户端总数
        value: 100
    trigger_size:   #触发器大小
        values: [16]
    bkd_ratio:      #投毒率
        values: [0.25]
    muil:
        values: [3.0]
    dataset:
        values: ['cifar10'] #cifar10, tiny-imagenet,GTSRB
    is_cam:
        values: [true]
    trigger_coord:
        values: ['significant'] #unsignificant, significant
    target_class:   #目标类别
        values: [2]
    is_poison:      #是否投毒训练
        value: true
    num_adversaries:    #攻击者数量
        values: [1]
    trigger_type:
        values: ['my'] #gaussian, fix,my

